### ISSUE TITLE
Error reading in Newick tree

### ISSUE THREAD

**Issue by mrhelmus** [DomBennett/treeman#1]
Dom,

I keep getting the following error when I try to assign a phylo object to TreeMan (v 1.1).

> Error in prinds[is.na(prinds)] <- root : replacement has length zero

The below code gives the error using the readTree function on my phylogeny

`txt<-"(Mimus_gilvus:42.797302,((((Coereba_flaveola:8.469427,Tiaris_bicolor:8.469427)Node5:8.287735,Sicalis_flaveola:16.757164)Node4:4.542213,(Setophaga_ruticilla:19.005642,(Zonotrichia_capensis:16.089878,(Quiscalus_major:13.013371,(Icterus_nigrogularis:8.389537,Icterus_icterus:8.389537)Node9:4.623834)Node8:3.076508)Node7:2.915765)Node6:2.293731)Node3:8.74406,Passer_domesticus:30.043432)Node2:12.753868)Node1:73.14138;"
readTree(text=txt)
`
Thanks!

**Comment by DomBennett** [comment]
Hi Matt,

Thanks for your interest in treeman and for raising this error. Hmmmm.... it appears I have not done my due diligence when considering the diversity of Newick tree possibilities. You can read in the file, but you'll need to remove the node labels and root edge. Below is some code to do just that through ape.

```r
txt<-"(Mimus_gilvus:42.797302,((((Coereba_flaveola:8.469427,Tiaris_bicolor:8.469427)Node5:8.287735,Sicalis_flaveola:16.757164)Node4:4.542213,(Setophaga_ruticilla:19.005642,(Zonotrichia_capensis:16.089878,(Quiscalus_major:13.013371,(Icterus_nigrogularis:8.389537,Icterus_icterus:8.389537)Node9:4.623834)Node8:3.076508)Node7:2.915765)Node6:2.293731)Node3:8.74406,Passer_domesticus:30.043432)Node2:12.753868)Node1:73.14138;"
tree <- ape::read.tree(text=txt)
tree$node.label <- NULL
tree$root.edge <- NULL
ape::write.tree(tree, file='temp.tre')
tree <- readTree(file='temp.tre')
summary(tree)
```

You can set the root edge manually post-hoc like so....

```r
# through treeman API
tree <- setNdSpn(tree, 'n20', 73.14138)
# or manually if you're feeling more adventurous
tree@ndlst[['n20']][['spn']] <- 73.14138
```

This is a bit piggy. I'll get to work on correcting `readTree` so that this error does not persist in v1.11. It should not be too difficult to correct.

Best,
Dom

**Comment by mrhelmus** [comment]
Ok great! Thanks for looking at this!

**Comment by DomBennett** [comment]
Hi Matt,

I've corrected the error on the GitHub version. You can download that so...

```r
devtools::install_github('dombennett/treeman')
```

Otherwise, I've just uploaded the latest version (1.11) with the corrections to CRAN which takes 1-2 days to become available on all the servers around the world.

The issue was to do with the handling of node labels (which I don't tend to use) in Newick. I've tested it now on >2,000 randomly downloaded trees from treebase. 

A quick note on your tree and node labels in Newick in general. It should read in fine. Upon running summary on it you'll notice there is an additional slot called 'Unknown'.

```R
> summary(tree)
Tree (TreeMan Object):
  + 10 tips
  + 9 internal nodes
  + Binary
  + PD 292
  + Root node is "n19"
  + With additional node slots:
    [Unknown]
```

It's reading the node1, node2.... etc. as special node information and is putting them in a user defined slot called 'Unknown'.

```R
> tree['Unknown']
        Mimus_gilvus     Coereba_flaveola       Tiaris_bicolor                   n4     Sicalis_flaveola 
                  NA                   NA                   NA              "Node5"                   NA 
                  n6  Setophaga_ruticilla Zonotrichia_capensis      Quiscalus_major Icterus_nigrogularis 
             "Node4"                   NA                   NA                   NA                   NA 
     Icterus_icterus                  n12                  n13                  n14                  n15 
                  NA              "Node9"              "Node8"              "Node7"              "Node6" 
                 n16    Passer_domesticus                  n18                  n19 
             "Node3"                   NA              "Node2"              "Node1" 
```

Given that the node labels don't contain any information of importance, I think you can just ignore them. But if you're interested, there's a bit more info and examples [here](https://github.com/DomBennett/treeman/wiki/Reading-and-writing) and [here](https://github.com/DomBennett/treeman/wiki/Writing-in-Newick-with-ndLabels()).

Anyway, thanks again for spotting this,
Dom
